name: Build OPcache for PHP 7.4 (macOS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew dependencies
        run: |
          brew install autoconf bison re2c

      - name: Install PHP 7.4 via Homebrew
        run: |
          brew install php@7.4

      - name: Ensure PHP 7.4 is in PATH
        run: |
          echo '/usr/local/opt/php@7.4/bin' >> $GITHUB_PATH
          echo '/usr/local/opt/php@7.4/sbin' >> $GITHUB_PATH

      - name: Verify phpize is available
        run: |
          phpize --version

      - name: Download PHP 7.4 source
        run: |
          curl -O https://www.php.net/distributions/php-7.4.33.tar.gz 
          tar zxpf php-7.4.33.tar.gz

      - name: Build OPcache extension
        run: |
          cd php-7.4.33/ext/opcache
          /usr/local/opt/php@7.4/bin/phpize
          ./configure --enable-opcache --with-php-config=/usr/local/opt/php@7.4/bin/php-config
          make

      - name: Package the result
        run: |
          cp php-7.4.33/ext/opcache/modules/opcache.so opcache.so
          zip -r opcache-macos-arm64.zip opcache.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: opcache-macos-arm64
          path: opcache-macos-arm64.zip
